/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAnimation: typeof import('./components/animations/BaseAnimation.vue')['default']
    BaseButton: typeof import('./components/inputs/BaseButton.vue')['default']
    BaseImg: typeof import('./components/media/BaseImg.vue')['default']
    BaseInputSelect: typeof import('./components/inputs/BaseInputSelect.vue')['default']
    BaseInputText: typeof import('./components/inputs/BaseInputText.vue')['default']
    DragElement: typeof import('./components/interact/DragElement.vue')['default']
    DropElement: typeof import('./components/interact/DropElement.vue')['default']
    ModalAtention: typeof import('./components/layout/ModalAtention.vue')['default']
    RobotAnimate: typeof import('./components/animations/RobotAnimate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechBubble: typeof import('./components/animations/SpeechBubble.vue')['default']
    TopBarControl: typeof import('./components/layout/TopBarControl.vue')['default']
  }
}
