/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAnimation: typeof import('./components/animations/BaseAnimation.vue')['default']
    BaseButton: typeof import('./components/inputs/BaseButton.vue')['default']
    RobotAnimate: typeof import('./components/animations/RobotAnimate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
